runtime: php
env: flex

runtime_config:
  document_root: public


skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:AuGrT6Vq26kIfzTSZRkUHzU/uUf0J42RzKK0y4DBtfs=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  DB_SOCKET: "/cloudsql/laratesting-222717:asia-south1:blog"

beta_settings:
  cloud_sql_instances: "laratesting-222717:asia-south1:blog"
